### ISSUE TITLE
Could not parse two types of dates

### ISSUE THREAD

**Issue by AviSassoon** [apoorv-mishra/moment-guess#1]
Hello dear author, great library i really like it,  very helpful tests, but unfortunately i found some issues:

Can not parse correctly "12-Jan-18" and "30/11/2017 14:45"
```js
it('should return one format DD-MMM-YY', () => {
    expect(guessFormat('12-Jan-18')).toBe('DD-MMM-YY');
});

it('should return one format DD/MM/YYYY HH:mm', () => {
    expect(guessFormat('30/11/2017 14:45')).toBe('DD/MM/YYYY HH:mm');
});

```

**Comment by apoorv-mishra** [comment]
Thanks for reporting @AviSassoon . I'll add support for these formats going further. Just curious, did you happen to use these formats in your own code somewhere?

**Comment by apoorv-mishra** [comment]
Hi @AviSassoon , the aforementioned formats have been supported as of `moment-guess@1.2.1`. Therefore, marking the issue as closed.
