### ISSUE TITLE
Typescript as dependency instead of devDependency

### ISSUE THREAD

**Issue by OlivierKamers** [apoorv-mishra/moment-guess#14]
Hi! 

We're interested in trying out this package but noticed that Typescript is listed as a dependency and not a devDependency. Usually it should not be needed at runtime. Was this intentional or can it be moved to the dev dependencies?

Thanks!

**Comment by apoorv-mishra** [comment]
Hi @OlivierKamers , thanks for raising the concern. I can't recall anything specific about this decision. Maybe it was just an oversight on my part. Regardless, I'll have a look into the issue and revert back.

**Comment by apoorv-mishra** [comment]
Fixed. Closing the issue.
