### ISSUE TITLE
Support for ambiguous input with date and time

### ISSUE THREAD

**Issue by mcrodrig** [apoorv-mishra/moment-guess#5]
Hi,

First, great idea to implement such library. I've been testing it for ambiguous input with only dates or times and it works great, but when I combined both I got an error.

Is this supported? If no, any plan to support it?

**Comment by apoorv-mishra** [comment]
Could you supply some examples? It would help to add support for those.

**Comment by mcrodrig** [comment]
Sure.

% npx -q moment-guess -d "01/01/2020"
INFO: Multiple formats matched!

DD/MM/YYYY
MM/DD/YYYY
% npx -q moment-guess -d "10:00"     
HH:mm
% npx -q moment-guess -d "10:00 am"
hh:mm a
% npx -q moment-guess -d "01/01/2020 10:00"
ERROR: Couldn't parse date

**Comment by apoorv-mishra** [comment]
Hi @mcrodrig , thanks for pointing out the issue. FYI, support has been added as of `moment-guess@1.1.1`. Marking it as closed. Re-open in case of any discrepancy.
